export const completionText = {
	Array: ['copy', 'fill', 'getStatistics', 'invert', 'sort', 'trim', 'concat', 'slice', 'print', 'reverse', 'rankPositions'],
	Dialog: ['create', 'addMessage', 'addString', 'addNumber', 'addCheckbox', 'addChoice', 'addSlider', 'show', 'getString',
		'getNumber', 'getCheckbox', 'getChoice'],
	File: ['append', 'close', 'dateLastModified', 'delete', 'directory', 'exists', 'getName', 'getParent', 'isDirectory',
		'lastModified', 'length', 'makeDirectory', 'name', 'nameWithoutExtension', 'open', 'openAsString', 'openAsRawString', 'openAsRawString',
		'openUrlAsString', 'openDialog', 'rename', 'saveString', 'separator'],
	Fit: ['doFit', 'rSquared', 'p', 'nParams', 'f', 'nEquations', 'getEquation', 'plot', 'logResults', 'showDialog'],
	IJ: ['deleteRows', 'getToolName', 'freeMemory', 'currentMemory', 'maxMemory', 'pad', 'redirectErrorMessages', 'renameResults'],
	List: ['set', 'get', 'getValue', 'size', 'clear', 'setList', 'getList', 'setMeasurements', 'setCommands'],
	Overlay: ['moveTo', 'lineTo', 'drawLine', 'add', 'setPosition', 'drawRect', 'drawEllipse', 'drawString', 'show', 'hide',
		'remove', 'size', 'removeSelection', 'copy', 'paste'],
	Plot: ['create', 'setLimits', 'setLineWidth', 'setColor', 'add', 'addText', 'setJustification', 'drawLine', 'show', 'update',
		'getValues', 'setFrameSize'],
	Stack: ['isHyperstack', 'getDimensions', 'setDimensions', 'setChannel', 'setSlice', 'setFrame', 'getPosition', 'setPosition',
		'getFrameRate', 'setFrameRate', 'getFrameInterval', 'setFrameInterval', 'getUnits', 'setTUnit', 'setZUnit', 'setDisplayMode', 'getDisplayMode',
		'setActiveChannels', 'getActiveChannels', 'swap', 'getStatistics'],
	String: ['resetBuffer', 'append', 'buffer', 'copy', 'copyResults', 'paste'],
};